
-- create
CREATE TABLE MYFRIENDS (
  ID INTEGER PRIMARY KEY,
  Name TEXT NOT NULL,
  YERSOLD INTEGER NOT NULL,
  ADRESS TEXT NOT NULL
);

-- insert
INSERT INTO MYFRIENDS VALUES (0001, 'Dima', '25', 'Kaliningrad');
INSERT INTO MYFRIENDS VALUES (0002, 'Danil', '30', 'Moskva');
INSERT INTO MYFRIENDS VALUES (0003, 'Ali', '32', 'Grozniy');

-- fetch 
SELECT * FROM MYFRIENDS WHERE ID = 0001;
